config/routes.rb
Rails.application.routes.draw do
  root: 'home#show'

end

app/models/home.rb
class Home < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def show
  #  @carousel = []
  #  carousel_directory = Dir.open "public/carousel"

  #  carousel_directory.each do |image|
  #    if image.length > 2
  #      @carousel.push("carousel/"+image)
  #    end
  #  end
  #  @home = Home.find(1)
  #  @title = @home.title
  #  @left_header = @home.left_header
  #  @left_body = @home.left_body
  #  @right_header = @home.right_header
  #  @right_body = @home.right_body
  end


  def edit
  #  @home = Home.find(1)
  end

  def update
  #  @home = Home.find(params[:id])
  #  if @home.update(home_params)
  #    redirect_to '/'
  #  else
  #    render :edit
  #  end
  end

  private
  def home_params
  #  params.require(:home).permit(:title, :left_header, :left_body, :right_header, :right_body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/edit.html.erb
THIS IS THE EDIT PAGE
<!--
<%= bootstrap_form_for @home do |f| %>
  <%= f.text_field :title, value: @home.title %>
  <%= f.text_field :left_header, value: @home.left_header %>
  <%= f.text_area :left_body, value: @home.left_body %>
  <%= f.text_field :right_header, value: @home.right_header %>
  <%= f.text_area :right_body, value: @home.right_body %>
  <%= f.submit %>
<% end %>
-->

app/views/home/show.html.erb
<h1>TEST PAGE</h1>
<!--
<h1> <%= @title %> </h1>

<% if user_signed_in? %>
  <%= link_to "Edit Home Page", edit_home_path(@home), class: "btn btn-sm btn-warning" %>
<% end %>

<div class="jumbotron">
  <div id="myCarousel" class="carousel slide">
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img class="image-responsive center-block" src="<%= @carousel[0] %> "alt="carousel image">
      </div>

      <div class="item">
        <img class="image-responsive center-block" src="<%= @carousel[1] %>" alt="carousel image">
      </div>

      <div class="item">
        <img class="image-responsive center-block" src="<%= @carousel[2] %>" alt="carousel image">
      </div>
    </div>

    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span><span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" role= aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

<div class="col-md-6 divided-column">
  <h3> <%= @left_header %> </h3>
  <br>
  <p><pre><%= @left_body %> </pre></p>

</div>

<div class="col-md-6">
  <h3> <%= @right_header %> </h3>
  <br>
  <p><pre><%= @right_body %> </pre></p>
</div>
-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>B3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>